version: '3.4'

services:
  productstore:
    image: ${DOCKER_REGISTRY-}productstore
    build:
      context: .
      dockerfile: ProductStore/Dockerfile
    #ports:
    #  - "6655:5085"
    #  - "6654:7085"
    restart: always 
    depends_on:
      - mssql

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    restart: always 